import { v4 as uuidv4 } from 'uuid';
/*
export const frontend = [
  {
    title: 'Internet',
    finished: false,
    id: uuidv4(),
    type: 'category',
    importance: 10,
    technologiesTags: [],
    goalDate: '20.01.2022',
    comments: ['this is hard'],
    resources: ['http://www.youtube.com'],
    order: true,
    recommended: 'recommended',
    children: [
      {
        title: 'How does the internet work?',
        finished: false,
        id: uuidv4(),
        type: 'element',
        importance: 5,
        technologiesTags: [],
        goalDate: '20.01.2022',
        comments: ['this is hard'],
        resources: ['http://www.youtube.com'],
        order: true,
        recommended: 'option' | 'recommended' | 'not-recommended',
        children: [],
      },
    ],
  },
];
*/

export interface Category {
  title: string;
  finished?: boolean;
  id: string;
  type: 'category' | 'element';
  importance?: number;
  technologiesTags?: string[];
  goalDate?: string;
  comments: string[];
  resources?: string[];
  order?: boolean;
  recommended?:
    | 'option'
    | 'recommended'
    | 'not-recommended'
    | 'not-strict'
    | 'not-recommended-option'
    | 'not-recommended-none'
    | 'none';
  children: Category[] | [];
  mainKnot?: boolean;
}

export const frontend: Category[] = [
  {
    title: 'Front-end',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    comments: [],
    children: [],
  },
  {
    title: 'Internet',
    type: 'category',
    finished: false,
    id: uuidv4(),
    importance: 10,
    technologiesTags: [],
    goalDate: '20.01.2022',
    comments: ['this is hard'],
    resources: ['http://www.youtube.com'],
    order: true,
    mainKnot: true,
    children: [
      {
        title: 'How does the internet work?',
        type: 'element',
        children: [],
        id: uuidv4(),
        finished: true,
        comments: [],
      },
      {
        title: 'What is Domain Name?',
        type: 'element',
        children: [],
        comments: ['Redo this', 'whats going on here', 'this is a comment'],
        id: uuidv4(),
        finished: false,
      },
      {
        title: 'What is hosting?',
        type: 'element',
        children: [],
        id: uuidv4(),
        finished: false,
        comments: [],
      },
      {
        title: 'DNS and how it works?',
        type: 'element',
        children: [],
        id: uuidv4(),
        finished: false,
        comments: [],
      },
      {
        title: 'What is HTTP?',
        type: 'element',
        children: [],
        id: uuidv4(),
        finished: false,
        comments: [],
      },
      {
        title: 'Browsers and how they work?',
        type: 'element',
        children: [],
        id: uuidv4(),
        finished: false,
        comments: [],
      },
    ],
  },
  {
    title: 'HTML',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    comments: [],
    children: [
      {
        title: 'Learn the basics',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
      },
      {
        title: 'Writing Semantic HTML',
        type: 'element',
        id: uuidv4(),
        recommended: 'not-strict',
        children: [],
        finished: false,
        comments: [],
      },
      {
        title: 'Forms and Validations',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
      },
      {
        title: 'Conventions and Best Practices',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
      },
      {
        title: 'Accessibility',
        type: 'element',
        id: uuidv4(),
        children: [],
        recommended: 'not-strict',
        finished: false,
        comments: [],
      },
      {
        title: 'SEO Basics',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        recommended: 'not-strict',
        comments: [],
      },
    ],
  },
  {
    title: 'CSS',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    comments: [],
    children: [
      {
        title: 'Learn the basics',
        type: 'element',
        id: uuidv4(),
        children: [],
        comments: [],
      },
      {
        title: 'Making Layouts',
        type: 'element',
        id: uuidv4(),
        finished: false,
        children: [],
        comments: [],
      },
      {
        title: 'Responsive design and Media Queries',
        type: 'element',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [
          {
            title: 'Floats',
            type: 'element',
            id: uuidv4(),
            finished: false,
            children: [],
            comments: [],
          },
          {
            title: 'Positioning',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'Display',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'Box Model',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'CSS Grid',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'Flex Box',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
        ],
      },
    ],
  },
  {
    title: 'Javascript',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    comments: [],
    children: [
      {
        title: 'Syntax and Basic Constructs',
        type: 'element',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Learn DOM Manipulation',
        type: 'element',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Learn Fetch API / Ajax (XHR)',
        type: 'element',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'ES6+ and modular Javascript',
        type: 'element',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Understand these concepts',
        type: 'element',
        finished: false,
        id: uuidv4(),
        comments: [],
        children: [
          {
            title: 'Hoisting',
            type: 'element',
            id: uuidv4(),
            finished: false,
            children: [],
            comments: [],
          },
          {
            title: 'Event Bubbling',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'Scope',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'Prototype',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'Shadow DOM',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'strict',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
        ],
      },
    ],
  },
  {
    title: 'Version Control Systems',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    comments: [],
    children: [
      {
        title: 'Repo hosting services',
        type: 'category',
        id: uuidv4(),
        recommended: 'none',
        finished: false,
        comments: [],
        children: [
          {
            title: 'GitHub',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'GitLab',
            type: 'element',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'not-recommended-option',
          },
          {
            title: 'Bitbucket',
            type: 'element',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'not-recommended-option',
          },
        ],
      },
      {
        title: 'Basic Usage of Git',
        type: 'category',
        id: uuidv4(),
        finished: false,
        children: [],
        comments: [],
      },
    ],
  },
  {
    title: 'Web Security Knowledge',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    recommended: 'not-strict',
    finished: false,
    comments: [],
    children: [
      {
        title: 'HTTPS',
        type: 'element',
        id: uuidv4(),
        children: [],
        comments: [],
        recommended: 'not-strict',
      },
      {
        title: 'Content Security Policy',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-strict',
      },
      {
        title: 'CORS',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-strict',
      },
      {
        title: 'OWASP Security Risks',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-strict',
      },
    ],
  },
  {
    title: 'Package Managers',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    comments: [],
    children: [
      {
        title: 'npm',
        type: 'element',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'yarn',
        type: 'element',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
    ],
  },
  {
    title: 'CSS Architecture',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    comments: [],
    children: [
      {
        title: 'BEM',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-strict',
      },
      {
        title: 'OOCSS',
        type: 'element',
        id: uuidv4(),
        children: [],
        comments: [],
        finished: false,
        recommended: 'not-recommended-none',
      },
      {
        title: 'SMACSS',
        type: 'element',
        id: uuidv4(),
        finished: false,
        children: [],
        comments: [],
        recommended: 'not-recommended-none',
      },
    ],
  },
  {
    title: 'CSS Preprocessors',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    comments: [],
    children: [
      {
        title: 'Sass',
        type: 'category',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-strict',
      },
      {
        title: 'PostCSS',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-strict',
      },
      {
        title: 'Less',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-recommended-none',
      },
    ],
  },
  {
    title: 'Build Tools',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    comments: [],
    children: [
      {
        title: 'Linters and Formatters',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [
          {
            title: 'Prettier',
            type: 'category',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'not-strict',
          },
          {
            title: 'ESLint',
            type: 'category',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'not-strict',
          },
          {
            title: 'StandardJS',
            type: 'category',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'not-recommended-none',
          },
        ],
      },
      {
        title: 'Task Runners',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [
          {
            title: 'npm scripts',
            type: 'category',
            id: uuidv4(),
            finished: false,
            children: [],
            comments: [],
          },
          {
            title: 'Gulp',
            type: 'element',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'not-recommended-none',
          },
        ],
      },
      {
        title: 'Module Bundlers',
        type: 'element',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [
          {
            title: 'Webpack',
            type: 'category',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'Rollup',
            type: 'element',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'option',
          },
          {
            title: 'Parcel',
            type: 'element',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'option',
          },
        ],
      },
    ],
  },
  {
    title: 'Pick a Framework',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    comments: [],
    children: [
      {
        title: 'React.js',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [
          {
            title: 'Redux',
            type: 'category',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'MobX',
            type: 'element',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'option',
          },
        ],
      },
      {
        title: 'Angular',
        type: 'element',
        id: uuidv4(),
        recommended: 'option',
        finished: false,
        comments: [],
        children: [
          {
            title: 'RxJS',
            type: 'category',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'option',
          },
          {
            title: 'NgRx',
            type: 'category',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'option',
          },
        ],
      },
      {
        title: 'Vue.js',
        type: 'element',
        id: uuidv4(),
        recommended: 'option',
        finished: false,
        comments: [],
        children: [
          {
            title: 'VueX',
            type: 'element',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'option',
          },
        ],
      },
    ],
  },
  {
    title: 'Modern CSS',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    comments: [],
    children: [
      {
        title: 'Styled Components',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'CSS Modules',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Styled JSX',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'option',
      },
      {
        title: 'Emotion',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'option',
      },
      {
        title: 'Radium',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-recommended-none',
      },
      {
        title: 'Glamorous',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-recommended-none',
      },
    ],
  },
  {
    title: 'Web Components',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    comments: [],
    recommended: 'not-strict',
    children: [
      {
        title: 'HTML Templates',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-strict',
      },
      {
        title: 'Custom Elements',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-strict',
      },
      {
        title: 'Shadow DOM',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-strict',
      },
    ],
  },
  {
    title: 'CSS Frameworks',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    comments: [],
    children: [
      {
        title: 'Reactstrap',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Material UI',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Tailwind CSS',
        type: 'category',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'option',
      },
      {
        title: 'Chakra UI',
        type: 'category',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'option',
      },
      {
        title: 'Bootstrap',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Materialize CSS',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'option',
      },
      {
        title: 'Bulma',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'option',
      },
    ],
  },
  {
    title: 'Testing your Apps',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    comments: [],
    children: [
      {
        title: 'Jest',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'react-testing-library',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Cypress',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Enzyme',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Mocha',
        type: 'category',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-recommended-none',
      },
      {
        title: 'Chai',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-recommended-none',
      },
      {
        title: 'Ava',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-recommended-none',
      },
      {
        title: 'Jasmine',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-recommended-none',
      },
    ],
  },
  {
    title: 'Type Checkers',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    recommended: 'not-strict',
    finished: false,
    comments: [],
    children: [
      {
        title: 'TypeScript',
        type: 'category',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-strict',
      },
      {
        title: 'Flow',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-recommended-none',
      },
    ],
  },
  {
    title: 'Progressive Web Apps',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    recommended: 'not-strict',
    comments: [],
    children: [
      {
        title: 'Calculating, Measuring, improving Performance',
        type: 'category',
        id: uuidv4(),
        recommended: 'not-strict',
        finished: false,
        comments: [],
        children: [
          {
            title: 'Storage',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'Web Sockets',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'Service Workers',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'Location',
            type: 'element',
            id: uuidv4(),
            comments: [],
            finished: false,
            children: [],
          },
          {
            title: 'Notifications',
            type: 'element',
            id: uuidv4(),
            comments: [],
            finished: false,
            children: [],
          },
          {
            title: 'Device Orientation',
            type: 'element',
            id: uuidv4(),
            comments: [],
            finished: false,
            children: [],
          },
          {
            title: 'Payments',
            type: 'element',
            id: uuidv4(),
            finished: false,
            children: [],
            comments: [],
          },
          {
            title: 'Credentials',
            type: 'element',
            id: uuidv4(),
            finished: false,
            children: [],
            comments: [],
          },
        ],
      },
      {
        title: "Web API's used in PWAs",
        type: 'category',
        id: uuidv4(),
        recommended: 'not-strict',
        finished: false,
        comments: [],
        children: [
          {
            title: 'PRPL Pattern',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'RAIL Model',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'Performance Metrics',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'Using Lighthouse',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'Using DevTools',
            type: 'element',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
        ],
      },
    ],
  },
  {
    title: 'Server Side Rendering',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    recommended: 'not-strict',
    finished: false,
    comments: [],
    children: [
      {
        title: 'React.js',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [
          {
            title: 'Next.js',
            type: 'category',
            id: uuidv4(),
            finished: false,
            comments: [],
            children: [],
          },
          {
            title: 'After.js',
            type: 'category',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'not-recommended-none',
          },
        ],
      },
      {
        title: 'Angular',
        type: 'element',
        id: uuidv4(),
        recommended: 'option',
        finished: false,
        comments: [],
        children: [
          {
            title: 'Universal',
            type: 'category',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'option',
          },
        ],
      },
      {
        title: 'Vue.js',
        type: 'element',
        id: uuidv4(),
        recommended: 'option',
        finished: false,
        comments: [],
        children: [
          {
            title: 'Nuxt.js',
            type: 'category',
            id: uuidv4(),
            children: [],
            finished: false,
            comments: [],
            recommended: 'option',
          },
        ],
      },
    ],
  },
  {
    title: 'GraphQL',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    recommended: 'not-strict',
    comments: [],
    children: [
      {
        title: 'Apollo',
        type: 'category',
        id: uuidv4(),
        finished: false,
        children: [],
        comments: [],
      },
      {
        title: 'Relay Modern',
        type: 'category',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'option',
      },
    ],
  },
  {
    title: 'Static Site Generators',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    recommended: 'not-strict',
    comments: [],
    children: [
      {
        title: 'Next.js',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'GatsbyJS',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Nuxt.js',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'option',
      },
      {
        title: 'Vuepress',
        type: 'element',
        id: uuidv4(),
        children: [],
        recommended: 'option',
        comments: [],
        finished: false,
      },
      {
        title: 'Jekyll',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'option',
      },
      {
        title: 'Hugo',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'option',
      },
    ],
  },
  {
    title: 'Mobile Applications',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    recommended: 'not-strict',
    comments: [],
    children: [
      {
        title: 'React Native',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Native Script',
        type: 'element',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Flutter',
        type: 'element',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Ionic',
        type: 'element',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
    ],
  },
  {
    title: 'Desktop Applications',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    finished: false,
    recommended: 'not-strict',
    comments: [],
    children: [
      {
        title: 'Electron',
        type: 'category',
        id: uuidv4(),
        finished: false,
        comments: [],
        children: [],
      },
      {
        title: 'Carlo',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-recommended-none',
      },
      {
        title: 'Proton Native',
        type: 'element',
        id: uuidv4(),
        children: [],
        finished: false,
        comments: [],
        recommended: 'not-recommended-none',
      },
    ],
  },
  {
    title: 'Web Assembly',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    children: [],
    finished: false,
    comments: [],
    recommended: 'not-strict',
  },
  {
    title: 'Keep Learning',
    type: 'category',
    id: uuidv4(),
    mainKnot: true,
    children: [],
    comments: [],
    finished: false,
  },
];
